# These are supported funding model platforms

github: [SrRapero720, NGoedix]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: srrapero720
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
custom: ['https://www.paypal.com/cgi-bin/webscr?return=https://www.curseforge.com/minecraft/mc-mods/watermedia&cn=Add+special+instructions+to+the+addon+author()&business=SrRapero720%40hotmail.com&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted&cancel_return=https://www.curseforge.com/minecraft/mc-mods/watermedia&lc=US&item_name=WATERMeDIA%3a+Multimedia+API+(from+www.curseforge.com)&cmd=_donations&rm=1&no_shipping=1&currency_code=USD', 'https://www.paypal.com/paypalme/ngoedix']
