modLoader="javafml"
loaderVersion="$neofmlrange"
issueTrackerURL="https://github.com/${github}/issues"
license="$license"
logoFile="pack.png"

[[mods]]
    modId="$id"
    version="$version"
    displayName="$simplename"
    displayTest="IGNORE_SERVER_VERSION"
    updateJSONURL="https://neoforge.curseupdate.com/869524/watermedia"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/watermedia"
    credits="$credits"
    authors="$authors"
    logoFile="pack.png"
    description='''$description'''